### PR TITLE
correct issue #43 and add more array helper method

### PR DESCRIPTION
**Pull request by tingshao**
1. change "point" to be "Point" in test/array/array.widl for issue #43
2. add FromArrayOfImplT method to enable creation of ArrayHelper from raw
   impl pointer array. And a new NewInstance method which carries a
   impl ptr parameter is added into NanXXX classes to enable creating
   NanXXX objects with existing impl ptrs.

@kenny-y

### CODE REVIEW

**Comment by kenny-y** [comment]
@tingshao That's a wonderful feature, I believe the team is thirsty of it. Thanks.

Just a quick question: has the FromArrayOfImplT() method and new NewInstance(T*)  method been tested?

**Comment by kenny-y** [comment]
BTW. Usually it'll be easier to manage our repo if we split multiple features/fixes into many small PRs, for this repo, we don't need to follow this rule all the time, though it'll be always nice to have small PRs :)

**Comment by tingshao** [comment]
@kenny-y you're right. Thanks for the review, I'll add the UT test.

**Comment by halton** [comment]
@tingshao the trybot is now enabled, please fix the related errors

**Pull request merged**
